# Imagen docker de Ubuntu con utilitarios genericos para operar un entorno Linux Ubuntu
FROM luchoalarcon/base:latest

LABEL maintainer = "Lucho Alarcon luis.omar.alarcon@gmail.com"

# install OPENJDK 18
RUN apt-get install -y openjdk-18-jdk

# update headers
RUN apt-get update
