# Imagen docker de Ubuntu con utilitarios genericos para operar un entorno Linux Ubuntu
FROM luchoalarcon/base:openjdk-18

LABEL maintainer = "Lucho Alarcon luis.omar.alarcon@gmail.com"

# update headers
RUN apt-get update
