name: Docker Image CD
on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push-image:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Log in to Docker HUB
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Metadata Base
      id: metadata-base
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKER_REPOSITORY_NAME }}/base
    
    - name: Build and push base image
      if: contains(github.event.head_commit.message, 'build=LATEST')
      uses: docker/build-push-action@v3
      with:
        context: ./latest
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY_NAME }}/base:latest
        labels: ${{ steps.metadata-base.outputs.labels }}

    - name: Build and push base image
      if: contains(github.event.head_commit.message, 'build=UTILS')
      uses: docker/build-push-action@v3
      with:
        context: ./utils
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY_NAME }}/base:utils
        labels: ${{ steps.metadata-base.outputs.labels }}

    - name: Build and push base image
      if: contains(github.event.head_commit.message, 'build=OPENJDK-18')
      uses: docker/build-push-action@v3
      with:
        context: ./openjdk-18
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY_NAME }}/base:openjdk-18
        labels: ${{ steps.metadata-base.outputs.labels }}

    - name: Build and push base image
      if: contains(github.event.head_commit.message, 'build=JENKINS')
      uses: docker/build-push-action@v3
      with:
        context: ./jenkins
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY_NAME }}/base:jenkins
        labels: ${{ steps.metadata-base.outputs.labels }}

    - name: Build and push base image
      if: contains(github.event.head_commit.message, 'build=JMETER-5.5')
      uses: docker/build-push-action@v3
      with:
        context: ./jmeter-5.5
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY_NAME }}/base:jmeter-5.5
        labels: ${{ steps.metadata-base.outputs.labels }}

    - name: Build and push base image
      if: contains(github.event.head_commit.message, 'build=AWS-CLI')
      uses: docker/build-push-action@v3
      with:
        context: ./aws-cli
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY_NAME }}/base:aws-cli
        labels: ${{ steps.metadata-base.outputs.labels }}
